import React from 'react';
import { X, FileText } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function DailySummaryModal({ summary, onClose }) {
  if (!summary) return null;

  return (
    <div className="fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div
        className="bg-aurivian-dark-gray rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto border border-aurivian-blue/30"
        onClick={e => e.stopPropagation()}
      >
        <div className="sticky top-0 bg-aurivian-dark-gray border-b border-aurivian-gray/20 p-4 flex items-center justify-between rounded-t-2xl">
          <div className="flex items-center gap-2">
            <FileText size={16} className="text-aurivian-blue" />
            <span className="text-aurivian-white font-medium">{summary.title}</span>
          </div>
          <button onClick={onClose} className="text-aurivian-gray hover:text-aurivian-white transition-colors">
            <X size={20} />
          </button>
        </div>
        <div className="p-6 prose prose-invert prose-sm max-w-none
          prose-headings:text-aurivian-white prose-h2:text-aurivian-blue prose-h3:text-aurivian-light-gray
          prose-p:text-aurivian-light-gray prose-strong:text-aurivian-white
          prose-table:text-aurivian-light-gray prose-th:text-aurivian-white prose-th:border-aurivian-gray/30
          prose-td:border-aurivian-gray/20
          prose-li:text-aurivian-light-gray
          prose-a:text-aurivian-blue
        ">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{summary.summary}</ReactMarkdown>
        </div>
        <div className="p-4 border-t border-aurivian-gray/20 text-center">
          <span className="text-[10px] text-aurivian-gray">Generated by Auri — Aurivian Congress Intelligence</span>
        </div>
      </div>
    </div>
  );
}
